### ISSUE TITLE
National domains resolving don't work

### ISSUE THREAD

**Issue by myxalov** [looterz/grimd#15]
Grimd don't work with national domains (e.g. russian cyrillic domain - дом.рф). Will it been fixed?

**Comment by a-a-m** [comment]
@myxalov Actually it works correctly now. No additional fixes needed.

Another question is how exactly you trying to ask? Look, you can't directly send request using "nslookup дом.рф" because "дом.рф" actually means "xn--d1aqf.xn--p1ai" (check for example at [Ru-Center](https://www.nic.ru/whois/?query=%E4%EE%EC.%F0%F4)).
 
From any modern web browser it works well out of box.

**Comment by myxalov** [comment]
We have a big list of domains, some of them on cyrillic. Grimd don't work with cyrillic domains.
How to solve this problem? Just convert cyrillic domains from list to this format - "xn--d1aqf.xn--p1ai"? How?

**Comment by a-a-m** [comment]
Yes, just convert your list of domains from Unicode to ASCII-Compatible Encoding (ACE) which is designed for use with Internationalized Domain Names (Punycode). Punycode transforms a Unicode sequence into a string of ASCII characters which can be used in a hostname label. Only letters, digits, and hyphens are allowed. Punycode sequences always start with the characters "XN--". format using any IDN converter.

In two words - you need any IDN Conversion Tool. For example, https://www.punycoder.com or http://mct.verisign-grs.com or any other.

**Comment by myxalov** [comment]
Can you recommend any converter for perl or python?

**Comment by a-a-m** [comment]
It's really simple to do by yourself:

Python
```python
a=u"дом.рф"
print a.encode("idna")
-> xn--d1aqf.xn--p1ai

print u"xn--d1aqf.xn--p1ai".decode("idna")
-> дом.рф
```

Sample code in Perl - http://s3blog.org/konvertacija-domena-v-zone-rf-v-punycode.html
