### ISSUE TITLE
Are the addresses of host-lists taken into account?

### ISSUE THREAD

**Issue by href** [looterz/grimd#23]
Sorry if this a bit of a dumb question, but does grimd merely block the domains it parses from the list, or is it possible that it might answer with a different ip address?

I'm asking because some of the host-lists seem to contain ip addresses. Now granted they all point to 127.0.0.1, but once I start using those lists as sources I have no guarantee that this will remain so. I could imagine that someone would rewrite a list to point some domain to another ip address.

So I could ask this in another way. Does grimd ignore the ip-addresses in the host-lists? I'd like to know that before trusting grimd with all my DNS requests.

Thanks :)

**Comment by emdioh** [comment]
It sound strange to me that some hotlists have IP addresses pointing to 127.0.0.1: maybe it's some of those hostnames like 123.123.123.123.some.domain.com?
In any case it should not matter because DNS is made to resolve IP addresses from hostnames: if a client is provided with an IP address it won't hit the DNS to resolve it.

**Comment by looterz** [comment]
grimd ignores any IP's specified in the hostlists and routes all requests to `nullroute` or `nullroutev6` depending on the protocol used.

**Comment by href** [comment]
That's what I hoped to hear @looterz . Thanks for confirming this and thank you for grimd!
